### ISSUE TITLE
Lacking Documentation

### ISSUE THREAD

**Issue by stephanellis** [rbreier/TheCellar#31]
I'm trying to dockerize this.  Why?  I'm getting pretty good with containers, but I want to try to containerize something that is way outside my area of expertise.  Can you update your docs to describe how someone can go from zero to running?  Specifically what your app needs in terms of configuration in order to run.

Thanks!

**Comment by rbreier** [comment]
I added a README to get you started.  But the headline # style used in IntelliJ doesn't seem to translate well on GitHub's website.  It should look pretty in your IDE.

**Comment by stephanellis** [comment]
Ok, cool thanks.  I won't be loading in the IDE, just building a Dockerfile and a compose file to see if I can containerize something I know nothing about.  Might even end up being useful to you.

**Comment by rbreier** [comment]
Definitely.  I look forward to seeing that. and learning about the process.
